version: '3.5'
services:
  db:
    image: mysql:8.0.23
    container_name: snaplitto-db
    env_file: ./.env
    volumes:
      - ~/mysql:/var/lib/mysql
    ports:
      - $SNAPLITTO_DB_INTERNAL_PORT:$SNAPLITTO_DB_EXTERNAL_PORT
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_HOST="%"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always
  service_api:
    depends_on:
      - db
    links:
      - db
    image: 'snapp-pay/snaplitto:latest'
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    container_name: snaplitto-service-api
    env_file: ./.env
    ports:
      - $SNAPLITTO_SERVICE_API_INTERNAL_PORT:$SNAPLITTO_SERVICE_API_EXTERNAL_PORT
    restart: on-failure
    environment:
      - DB_HOST=snaplitto-db
      - DB_PORT=$SNAPLITTO_DB_EXTERNAL_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
#    working_dir: /app
#    command: [sh, -c, 'mkdir -p ~/logs/; cd /src; mvn clean -P docker spring-boot:run']
    networks:
      - net
    volumes:
      - "${HOME}/.m2:/root/.m2"
networks:
  net:
    driver: bridge
